'use client';
import { useState } from 'react';
import { useDashboardStore } from '@/stores/useDashboardStore';
import { Trophy, ArrowRight, Loader2 } from 'lucide-react';

import { auth } from '@/lib/firebase';
import { useGamificationStore } from '@/stores/useGamificationStore';

export default function DailyChallenge() {
  const [loading, setLoading] = useState(false);
  const { challengeStarted, challengeScore, challengeIndex, challengeComplete, startChallenge, setChallengeScore, nextChallengeQuestion, completeChallenge } = useDashboardStore();
  
  const [questions, setQuestions] = useState<any[]>([]);

  const handleStart = async () => {
    setLoading(true);
    try {
      const token = await auth.currentUser?.getIdToken();
      const res = await fetch('/api/ai/challenge', {
        headers: { Authorization: `Bearer ${token}` }
      });
      const data = await res.json();
      if (data.questions) {
        setQuestions(data.questions);
        startChallenge();
      }
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleAnswer = (idx: number) => {
    if (idx === questions[challengeIndex].answer) {
      setChallengeScore(challengeScore + 1);
    }
    if (challengeIndex < questions.length - 1) {
      nextChallengeQuestion();
    } else {
      completeChallenge();
      // Update XP via Gamification API
      const uid = auth.currentUser?.uid;
      if (uid) {
        useGamificationStore.getState().syncWithFirebase(uid, 'DAILY_CHALLENGE');
      } else {
        useGamificationStore.getState().addXP(10, 'Daily Challenge', 'DAILY_CHALLENGE');
      }
    }
  };

  if (challengeComplete) {
    return (
      <div className="bg-gradient-to-br from-brand-purple to-brand-violet rounded-2xl p-6 text-white shadow-lg">
        <div className="flex items-center gap-3 mb-4">
          <Trophy className="w-8 h-8 text-yellow-300" />
          <h2 className="text-xl font-bold">Challenge Complete!</h2>
        </div>
        <p className="text-brand-purple/20 bg-white/10 rounded-lg p-4 font-medium backdrop-blur-sm mb-4">
          You scored {challengeScore}/{questions.length} today.
        </p>
        <div className="text-sm text-white/80">Come back tomorrow for a new challenge!</div>
      </div>
    );
  }

  if (challengeStarted && questions.length > 0) {
    const q = questions[challengeIndex];
    return (
      <div className="bg-white rounded-2xl p-6 shadow-sm border border-slate-200">
        <div className="flex justify-between text-sm font-medium text-slate-500 mb-4">
          <span>Question {challengeIndex + 1} of {questions.length}</span>
          <span className="text-brand-purple font-bold">Score: {challengeScore}</span>
        </div>
        <h3 className="text-lg font-bold text-slate-800 mb-6">{q.q}</h3>
        <div className="flex flex-col gap-3">
          {q.options.map((opt: string, i: number) => (
            <button 
              key={i}
              onClick={() => handleAnswer(i)}
              className="text-left w-full p-4 rounded-xl border border-slate-200 hover:border-brand-purple hover:bg-brand-purple/5 transition-all font-medium text-slate-700"
            >
              {opt}
            </button>
          ))}
        </div>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-2xl p-6 shadow-sm border border-slate-200">
      <div className="flex items-center gap-3 mb-2">
        <div className="p-2 bg-brand-purple/10 rounded-lg">
          <Trophy className="w-6 h-6 text-brand-purple" />
        </div>
        <h2 className="text-lg font-bold text-slate-800">Daily AI Challenge</h2>
      </div>
      <p className="text-slate-500 text-sm mb-6 mt-2">
        Complete 5 quick questions generated by Gemini AI to earn 50 bonus XP today.
      </p>
      <button 
        onClick={handleStart}
        disabled={loading}
        className="w-full flex items-center justify-center gap-2 bg-slate-900 text-white rounded-xl py-3 font-medium hover:bg-slate-800 transition-colors disabled:opacity-70"
      >
        {loading ? <Loader2 className="w-5 h-5 animate-spin" /> : (
          <>Start Challenge <ArrowRight className="w-4 h-4" /></>
        )}
      </button>
    </div>
  );
}
