const fs = require('fs');
const file = 'c:/Users/HP/OneDrive/Desktop/ChemLearn AI/frontend/resources.html';
let content = fs.readFileSync(file, 'utf8');

const ptHTML = `
    <!-- INTERACTIVE PERIODIC TABLE -->
    <div style="max-width: 1200px; width: 92%; margin: 60px auto 40px auto; position: relative;">
        <h2 style="font-size: 1.8rem; font-weight: 800; color: #1e1b4b; margin-bottom: 8px;">Interactive Periodic Table</h2>
        <p style="color: #64748b; font-size: 0.95rem; margin-bottom: 24px;">Explore the building blocks of matter. Click any element to learn more.</p>

        <div class="periodic-table-container">
            <div class="periodic-table" id="periodicTable">
                <!-- Elements generated by JS -->
            </div>
        </div>
    </div>

    <!-- PERIODIC TABLE MODAL -->
    <div class="pt-modal" id="ptModal" onclick="closePTModal()">
        <div class="pt-modal-content" onclick="event.stopPropagation()">
            <button class="pt-close-btn" onclick="closePTModal()">&times;</button>
            <div class="pt-modal-symbol" id="ptModalSymbol">H</div>
            <div class="pt-modal-name" id="ptModalName">Hydrogen</div>
            <div class="pt-modal-category" id="ptModalCategory">Non-Metal</div>
            
            <div class="pt-modal-details">
                <div class="pt-stat-box">
                    <div class="pt-stat-label">Atomic Number</div>
                    <div class="pt-stat-value" id="ptModalZ">1</div>
                </div>
                <div class="pt-stat-box">
                    <div class="pt-stat-label">Atomic Mass</div>
                    <div class="pt-stat-value" id="ptModalMass">1.008</div>
                </div>
            </div>
            <div class="pt-modal-desc" id="ptModalDesc">
                Hydrogen is the lightest element and the most abundant chemical substance in the universe.
            </div>
        </div>
    </div>
`;

const footerIdx = content.indexOf('<footer class="footer-wrapper">');
content = content.substring(0, footerIdx) + ptHTML + content.substring(footerIdx);

const jsHTML = `
        // --- PERIODIC TABLE LOGIC ---
        const elementsData = [
            { z: 1, symbol: 'H', name: 'Hydrogen', mass: '1.008', col: 1, row: 1, cat: 'non-metal', desc: 'Lightest element, highly flammable.' },
            { z: 2, symbol: 'He', name: 'Helium', mass: '4.0026', col: 18, row: 1, cat: 'noble-gas', desc: 'Inert gas, second most abundant element.' },
            
            { z: 3, symbol: 'Li', name: 'Lithium', mass: '6.94', col: 1, row: 2, cat: 'alkali-metal', desc: 'Lightest metal, highly reactive.' },
            { z: 4, symbol: 'Be', name: 'Beryllium', mass: '9.0122', col: 2, row: 2, cat: 'alkaline-earth', desc: 'Hard, lightweight metal used in aerospace.' },
            { z: 5, symbol: 'B', name: 'Boron', mass: '10.81', col: 13, row: 2, cat: 'metalloid', desc: 'Important in plant cell walls, used in glass.' },
            { z: 6, symbol: 'C', name: 'Carbon', mass: '12.011', col: 14, row: 2, cat: 'non-metal', desc: 'Basis of all known life, forms many allotropes.' },
            { z: 7, symbol: 'N', name: 'Nitrogen', mass: '14.007', col: 15, row: 2, cat: 'non-metal', desc: 'Makes up 78% of Earth\\'s atmosphere.' },
            { z: 8, symbol: 'O', name: 'Oxygen', mass: '15.999', col: 16, row: 2, cat: 'non-metal', desc: 'Crucial for respiration and combustion.' },
            { z: 9, symbol: 'F', name: 'Fluorine', mass: '18.998', col: 17, row: 2, cat: 'halogen', desc: 'Most electronegative element, highly reactive.' },
            { z: 10, symbol: 'Ne', name: 'Neon', mass: '20.180', col: 18, row: 2, cat: 'noble-gas', desc: 'Inert gas, glows reddish-orange in signs.' },
            
            { z: 11, symbol: 'Na', name: 'Sodium', mass: '22.990', col: 1, row: 3, cat: 'alkali-metal', desc: 'Highly reactive metal, crucial for nerve function.' },
            { z: 12, symbol: 'Mg', name: 'Magnesium', mass: '24.305', col: 2, row: 3, cat: 'alkaline-earth', desc: 'Burns with a brilliant white light.' },
            { z: 13, symbol: 'Al', name: 'Aluminum', mass: '26.982', col: 13, row: 3, cat: 'post-transition', desc: 'Light, strong, widely used metal.' },
            { z: 14, symbol: 'Si', name: 'Silicon', mass: '28.085', col: 14, row: 3, cat: 'metalloid', desc: 'Essential semiconductor used in electronics.' },
            { z: 15, symbol: 'P', name: 'Phosphorus', mass: '30.974', col: 15, row: 3, cat: 'non-metal', desc: 'Highly reactive, exists in white and red forms.' },
            { z: 16, symbol: 'S', name: 'Sulfur', mass: '32.06', col: 16, row: 3, cat: 'non-metal', desc: 'Yellow non-metal, used in sulfuric acid.' },
            { z: 17, symbol: 'Cl', name: 'Chlorine', mass: '35.45', col: 17, row: 3, cat: 'halogen', desc: 'Toxic green gas, used as a disinfectant.' },
            { z: 18, symbol: 'Ar', name: 'Argon', mass: '39.95', col: 18, row: 3, cat: 'noble-gas', desc: 'Inert gas used in lightbulbs.' },

            { z: 19, symbol: 'K', name: 'Potassium', mass: '39.098', col: 1, row: 4, cat: 'alkali-metal', desc: 'Reacts violently with water.' },
            { z: 20, symbol: 'Ca', name: 'Calcium', mass: '40.078', col: 2, row: 4, cat: 'alkaline-earth', desc: 'Essential for bones and teeth.' },
            { z: 21, symbol: 'Sc', name: 'Scandium', mass: '44.956', col: 3, row: 4, cat: 'transition-metal', desc: 'Light transition metal.' },
            { z: 22, symbol: 'Ti', name: 'Titanium', mass: '47.867', col: 4, row: 4, cat: 'transition-metal', desc: 'Strong, lightweight, corrosion-resistant.' },
            { z: 23, symbol: 'V', name: 'Vanadium', mass: '50.942', col: 5, row: 4, cat: 'transition-metal', desc: 'Used in steel alloys.' },
            { z: 24, symbol: 'Cr', name: 'Chromium', mass: '51.996', col: 6, row: 4, cat: 'transition-metal', desc: 'Very hard, used for plating.' },
            { z: 25, symbol: 'Mn', name: 'Manganese', mass: '54.938', col: 7, row: 4, cat: 'transition-metal', desc: 'Important industrial alloy element.' },
            { z: 26, symbol: 'Fe', name: 'Iron', mass: '55.845', col: 8, row: 4, cat: 'transition-metal', desc: 'Most common element forming Earth\\'s mass.' },
            { z: 27, symbol: 'Co', name: 'Cobalt', mass: '58.933', col: 9, row: 4, cat: 'transition-metal', desc: 'Magnetic metal, used in batteries.' },
            { z: 28, symbol: 'Ni', name: 'Nickel', mass: '58.693', col: 10, row: 4, cat: 'transition-metal', desc: 'Corrosion resistant, used in coins.' },
            { z: 29, symbol: 'Cu', name: 'Copper', mass: '63.546', col: 11, row: 4, cat: 'transition-metal', desc: 'Excellent electrical conductor.' },
            { z: 30, symbol: 'Zn', name: 'Zinc', mass: '65.38', col: 12, row: 4, cat: 'transition-metal', desc: 'Used to galvanize steel.' },
            { z: 31, symbol: 'Ga', name: 'Gallium', mass: '69.723', col: 13, row: 4, cat: 'post-transition', desc: 'Melts in your hand.' },
            { z: 32, symbol: 'Ge', name: 'Germanium', mass: '72.630', col: 14, row: 4, cat: 'metalloid', desc: 'Important semiconductor.' },
            { z: 33, symbol: 'As', name: 'Arsenic', mass: '74.922', col: 15, row: 4, cat: 'metalloid', desc: 'Notorious poison, also used in semiconductors.' },
            { z: 34, symbol: 'Se', name: 'Selenium', mass: '78.971', col: 16, row: 4, cat: 'non-metal', desc: 'Used in photocopiers and glassmaking.' },
            { z: 35, symbol: 'Br', name: 'Bromine', mass: '79.904', col: 17, row: 4, cat: 'halogen', desc: 'Red-brown liquid at room temperature.' },
            { z: 36, symbol: 'Kr', name: 'Krypton', mass: '83.798', col: 18, row: 4, cat: 'noble-gas', desc: 'Used in high-speed photography.' }
        ];

        window.addEventListener('load', () => {
            const table = document.getElementById('periodicTable');
            if(table) {
                elementsData.forEach(el => {
                    const card = document.createElement('div');
                    card.className = \element-card \\;
                    card.style.gridColumn = el.col;
                    card.style.gridRow = el.row;
                    
                    card.innerHTML = \
                        <div class="element-number">\</div>
                        <div class="element-symbol">\</div>
                        <div class="element-name">\</div>
                    \;
                    
                    card.onclick = () => openPTModal(el);
                    table.appendChild(card);
                });
            }
        });

        window.openPTModal = function(el) {
            document.getElementById('ptModalSymbol').textContent = el.symbol;
            document.getElementById('ptModalName').textContent = el.name;
            document.getElementById('ptModalCategory').textContent = el.cat.replace('-', ' ').replace(/\\b\\w/g, l => l.toUpperCase());
            document.getElementById('ptModalZ').textContent = el.z;
            document.getElementById('ptModalMass').textContent = el.mass;
            document.getElementById('ptModalDesc').textContent = el.desc;
            
            // Set colors dynamically based on category
            const catColors = {
                'non-metal': '#bae6fd',
                'alkali-metal': '#fecaca',
                'alkaline-earth': '#fde68a',
                'transition-metal': '#e9d5ff',
                'post-transition': '#bbf7d0',
                'metalloid': '#fde047',
                'halogen': '#fed7aa',
                'noble-gas': '#c7d2fe'
            };
            document.getElementById('ptModalCategory').style.background = catColors[el.cat] || '#e2e8f0';

            document.getElementById('ptModal').classList.add('active');
        };

        window.closePTModal = function() {
            document.getElementById('ptModal').classList.remove('active');
        };
`;

const scriptMarker = '})();';
const lastScriptIdx = content.lastIndexOf(scriptMarker);
content = content.substring(0, lastScriptIdx + scriptMarker.length) + jsHTML + content.substring(lastScriptIdx + scriptMarker.length);

fs.writeFileSync(file, content);
console.log("Done");
